services:
  wapp:
    container_name: wapp  
    build: ./php
    volumes:
      - ./nginx/src:/var/www
  wnginx:
    image: nginx 
    container_name: wnginx
    ports:
      - 8000:80 
    volumes:
      - ./nginx/src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/work
    depends_on:
      - wapp
  wdb:
    image: mysql:8.0
    container_name: wdb
    environment: 
      MYSQL_ROOT_PASSWORD: db-user
      MYSQL_DATABASE: work
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-user

      TZ: 'Asia/Tokyo' 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  db-store: